<p style ="text-align:center">
    <img src="http://epecora.com.br/DataFiles/BannerUFPR.png" width="700" alt="PPGOLD/PPGMNE Python:INTRO"  />
</p>

## Prof. Eduardo Pécora, Ph.D.

# Pandas: Resumão dos principais métodos

Nesta aula apresentaremos mais de 25 métodos do Pandas para manipulação dos dados do DataFrame

In [47]:
import pandas as pd
import numpy as np

# Sample data
data1 = {'Country': ['USA', 'China', 'India', 'Brazil'],
         'Population_2000': [281421906, 1262645000, 1056570000, 174468575],
         'Population_2010': [308745538, 1337705000, 1230985000, 190755799],
         'Population_2020': [335946003,1424798421 , 1383112050, 213196304]}

data2 = {'Country': ['Russia', 'Japan', 'Germany', 'United Kingdom'],
         'Population_2000': [14676276, 126911000, 82431300, 59615200],
         'Population_2010': [142958000, 128057352, 81802257, 62766365],
         'Population_2020': [145617329,125244761 , 83328988, 66788659]}

# https://www.worldometers.info/world-population/population-by-country/

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

## Concatenate dois ou mais DFs

In [48]:
# Concatenating DataFrames
combined_df = pd.concat([df1, df2], ignore_index=True)
combined_df

          Country  Population_2000  Population_2010  Population_2020
0             USA        281421906        308745538        335946003
1           China       1262645000       1337705000       1424798421
2           India       1056570000       1230985000       1383112050
3          Brazil        174468575        190755799        213196304
4          Russia         14676276        142958000        145617329
5           Japan        126911000        128057352        125244761
6         Germany         82431300         81802257         83328988
7  United Kingdom         59615200         62766365         66788659

### Adicina uma nova linha no final

In [49]:
from IPython.display import display

# Exibir o DataFrame como tabela
display(combined_df.dtypes)

Country            object
Population_2000     int64
Population_2010     int64
Population_2020     int64
dtype: object

In [50]:
# Adding a row value
combined_df.loc[combined_df.shape[0]] = ['France', np.nan, np.nan,np.nan]
combined_df

          Country  Population_2000  Population_2010  Population_2020
0             USA      281,421,906      308,745,538      335,946,003
1           China    1,262,645,000    1,337,705,000    1,424,798,421
2           India    1,056,570,000    1,230,985,000    1,383,112,050
3          Brazil      174,468,575      190,755,799      213,196,304
4          Russia       14,676,276      142,958,000      145,617,329
5           Japan      126,911,000      128,057,352      125,244,761
6         Germany       82,431,300       81,802,257       83,328,988
7  United Kingdom       59,615,200       62,766,365       66,788,659
8          France              NaN              NaN              NaN

In [51]:
combined_df.dtypes

Country             object
Population_2000    float64
Population_2010    float64
Population_2020    float64
dtype: object

### Peencher os valores ausentes com Zero

In [52]:
# Filling missing values with 0 and disabling scientific notation
pd.options.display.float_format = '{:,.0f}'.format
filled_df = combined_df.fillna(0)
filled_df

          Country  Population_2000  Population_2010  Population_2020
0             USA      281,421,906      308,745,538      335,946,003
1           China    1,262,645,000    1,337,705,000    1,424,798,421
2           India    1,056,570,000    1,230,985,000    1,383,112,050
3          Brazil      174,468,575      190,755,799      213,196,304
4          Russia       14,676,276      142,958,000      145,617,329
5           Japan      126,911,000      128,057,352      125,244,761
6         Germany       82,431,300       81,802,257       83,328,988
7  United Kingdom       59,615,200       62,766,365       66,788,659
8          France                0                0                0

### Selecionar as colunas `numeric` e calcular as médias

In [53]:
mean_values = combined_df.select_dtypes(include='number').mean()
mean_values

Population_2000   382,342,407
Population_2010   435,471,914
Population_2020   472,254,064
dtype: float64

### Preenchendo os valores ausentes com a média

In [54]:
# Filling missing values with average
filled_df = combined_df.fillna(mean_values)
filled_df

          Country  Population_2000  Population_2010  Population_2020
0             USA      281,421,906      308,745,538      335,946,003
1           China    1,262,645,000    1,337,705,000    1,424,798,421
2           India    1,056,570,000    1,230,985,000    1,383,112,050
3          Brazil      174,468,575      190,755,799      213,196,304
4          Russia       14,676,276      142,958,000      145,617,329
5           Japan      126,911,000      128,057,352      125,244,761
6         Germany       82,431,300       81,802,257       83,328,988
7  United Kingdom       59,615,200       62,766,365       66,788,659
8          France      382,342,407      435,471,914      472,254,064

## `Melt` um DF

### Transformar colunas em linhas

In [55]:
# Melting the DataFrame
melted_df = pd.melt(filled_df, id_vars=['Country'], var_name='Year', value_name='Population')

print(melted_df)

           Country             Year    Population
0              USA  Population_2000   281,421,906
1            China  Population_2000 1,262,645,000
2            India  Population_2000 1,056,570,000
3           Brazil  Population_2000   174,468,575
4           Russia  Population_2000    14,676,276
5            Japan  Population_2000   126,911,000
6          Germany  Population_2000    82,431,300
7   United Kingdom  Population_2000    59,615,200
8           France  Population_2000   382,342,407
9              USA  Population_2010   308,745,538
10           China  Population_2010 1,337,705,000
11           India  Population_2010 1,230,985,000
12          Brazil  Population_2010   190,755,799
13          Russia  Population_2010   142,958,000
14           Japan  Population_2010   128,057,352
15         Germany  Population_2010    81,802,257
16  United Kingdom  Population_2010    62,766,365
17          France  Population_2010   435,471,914
18             USA  Population_2020   335,946,003
19           China  Population_2020 1,424,798,421
20           India  Population_2020 1,383,112,050
21          Brazil  Population_2020   213,196,304
22          Russia  Population_2020   145,617,329
23           Japan  Population_2020   125,244,761
24         Germany  Population_2020    83,328,988
25  United Kingdom  Population_2020    66,788,659
26          France  Population_2020   472,254,064

### `Apply` uma função

In [56]:
# Define a function to convert population to billions
def to_billion(population):
    return population / 1_000_000_000

# Apply the function to Population columns
filled_df['Population_2000_Billion'] = filled_df['Population_2000'].apply(to_billion)
filled_df['Population_2010_Billion'] = filled_df['Population_2010'].apply(to_billion)
filled_df['Population_2020_Billion'] = filled_df['Population_2020'].apply(to_billion)

print(filled_df)

          Country  Population_2000  Population_2010  Population_2020  \
0             USA      281,421,906      308,745,538      335,946,003
1           China    1,262,645,000    1,337,705,000    1,424,798,421
2           India    1,056,570,000    1,230,985,000    1,383,112,050
3          Brazil      174,468,575      190,755,799      213,196,304
4          Russia       14,676,276      142,958,000      145,617,329
5           Japan      126,911,000      128,057,352      125,244,761
6         Germany       82,431,300       81,802,257       83,328,988
7  United Kingdom       59,615,200       62,766,365       66,788,659
8          France      382,342,407      435,471,914      472,254,064

   Population_2000_Billion  Population_2010_Billion  Population_2020_Billion
0                        0                        0                        0
1                        1                        1                        1
2                        1                        1                        1
3                        0                        0                        0
4                        0                        0                        0
5                        0                        0                        0
6                        0                        0                        0
7                        0                        0                        0
8                        0                        0                        0

### `Drop` Columns

In [57]:
# Drop the Population columns
dropped_df = filled_df.drop(columns=['Population_2000', 'Population_2010','Population_2020'])

print(dropped_df)

          Country  Population_2000_Billion  Population_2010_Billion  \
0             USA                        0                        0
1           China                        1                        1
2           India                        1                        1
3          Brazil                        0                        0
4          Russia                        0                        0
5           Japan                        0                        0
6         Germany                        0                        0
7  United Kingdom                        0                        0
8          France                        0                        0

   Population_2020_Billion
0                        0
1                        1
2                        1
3                        0
4                        0
5                        0
6                        0
7                        0
8                        0

### loc[]

In [58]:
# Accessing data for 'USA' in 'Country' column
usa_data = dropped_df.loc[dropped_df['Country'] == 'USA']

print(usa_data)

  Country  Population_2000_Billion  Population_2010_Billion  \
0     USA                        0                        0

   Population_2020_Billion
0                        0

### `isin`

In [59]:
# Accessing data for 'USA','Brazil' and 'France' in 'Country' column
UBF_data = dropped_df.loc[dropped_df['Country'].isin(['USA','Brazil',"France"])]

print(UBF_data)

  Country  Population_2000_Billion  Population_2010_Billion  \
0     USA                        0                        0
3  Brazil                        0                        0
8  France                        0                        0

   Population_2020_Billion
0                        0
3                        0
8                        0

### `reset_index`

In [60]:
print("Before Index Reseting\n", UBF_data)
UBF_data.reset_index(inplace=True, drop=True)
print("After Index Reseting\n", UBF_data)

Before Index Reseting
   Country  Population_2000_Billion  Population_2010_Billion  \
0     USA                        0                        0
3  Brazil                        0                        0
8  France                        0                        0

   Population_2020_Billion
0                        0
3                        0
8                        0
After Index Reseting
   Country  Population_2000_Billion  Population_2010_Billion  \
0     USA                        0                        0
1  Brazil                        0                        0
2  France                        0                        0

   Population_2020_Billion
0                        0
1                        0
2                        0

### `values_counts`

In [61]:
#Double some rows
df_double = pd.concat([dropped_df, UBF_data], axis=0)
df_double

,Country,Population_2000_Billion,Population_2010_Billion,Population_2020_Billion
0,USA,0,0,0
1,China,1,1,1
2,India,1,1,1
3,Brazil,0,0,0
4,Russia,0,0,0
5,Japan,0,0,0
6,Germany,0,0,0
7,United Kingdom,0,0,0
8,France,0,0,0
0,USA,0,0,0
1,Brazil,0,0,0
2,France,0,0,0

In [62]:
# Counting occurrences of each country
country_counts = df_double['Country'].value_counts()
print(country_counts)

Country
USA               2
Brazil            2
France            2
India             1
China             1
Russia            1
Japan             1
Germany           1
United Kingdom    1
Name: count, dtype: int64

### `unique`

In [63]:
# Getting unique countries
unique_countries = df_double['Country'].unique()
print(unique_countries)

['USA' 'China' 'India' 'Brazil' 'Russia' 'Japan' 'Germany'
 'United Kingdom' 'France']

### `drop_duplicates`

In [64]:
# Removendo linhas duplicadas com base na coluna 'Country'
base_df = df_double.drop_duplicates(subset='Country')

print(base_df)

          Country  Population_2000_Billion  Population_2010_Billion  \
0             USA                        0                        0
1           China                        1                        1
2           India                        1                        1
3          Brazil                        0                        0
4          Russia                        0                        0
5           Japan                        0                        0
6         Germany                        0                        0
7  United Kingdom                        0                        0
8          France                        0                        0

   Population_2020_Billion
0                        0
1                        1
2                        1
3                        0
4                        0
5                        0
6                        0
7                        0
8                        0

### `astype`

In [65]:
# Melting o DataFrame
melted_df = pd.melt(base_df, id_vars=['Country'], var_name='Year', value_name='Population')
print(melted_df)

# Criando um nova coluna Year
melted_df["Year"]=melted_df["Year"].str[11:15]
print(melted_df)

# Aplicando o método `astype` na coluna `Year`
print("Tipos ANTES a conversão\n",melted_df.dtypes)

melted_df['Year'] = melted_df['Year'].astype(int)

print("Tipos APÓS a conversão\n",melted_df.dtypes)

           Country                     Year  Population
0              USA  Population_2000_Billion           0
1            China  Population_2000_Billion           1
2            India  Population_2000_Billion           1
3           Brazil  Population_2000_Billion           0
4           Russia  Population_2000_Billion           0
5            Japan  Population_2000_Billion           0
6          Germany  Population_2000_Billion           0
7   United Kingdom  Population_2000_Billion           0
8           France  Population_2000_Billion           0
9              USA  Population_2010_Billion           0
10           China  Population_2010_Billion           1
11           India  Population_2010_Billion           1
12          Brazil  Population_2010_Billion           0
13          Russia  Population_2010_Billion           0
14           Japan  Population_2010_Billion           0
15         Germany  Population_2010_Billion           0
16  United Kingdom  Population_2010_Billion           0
17          France  Population_2010_Billion           0
18             USA  Population_2020_Billion           0
19           China  Population_2020_Billion           1
20           India  Population_2020_Billion           1
21          Brazil  Population_2020_Billion           0
22          Russia  Population_2020_Billion           0
23           Japan  Population_2020_Billion           0
24         Germany  Population_2020_Billion           0
25  United Kingdom  Population_2020_Billion           0
26          France  Population_2020_Billion           0
           Country  Year  Population
0              USA  2000           0
1            China  2000           1
2            India  2000           1
3           Brazil  2000           0
4           Russia  2000           0
5            Japan  2000           0
6          Germany  2000           0
7   United Kingdom  2000           0
8           France  2000           0
9              USA  2010           0
10           China  2010           1
11           India  2010           1
12          Brazil  2010           0
13          Russia  2010           0
14           Japan  2010           0
15         Germany  2010           0
16  United Kingdom  2010           0
17          France  2010           0
18             USA  2020           0
19           China  2020           1
20           India  2020           1
21          Brazil  2020           0
22          Russia  2020           0
23           Japan  2020           0
24         Germany  2020           0
25  United Kingdom  2020           0
26          France  2020           0
Tipos ANTES a conversão
 Country        object
Year           object
Population    float64
dtype: object
Tipos APÓS a conversão
 Country        object
Year            int64
Population    float64
dtype: object

### `to_datetime`

In [66]:
# Criando uma nova coluna 'Year_date' e convertendo para tipo de dados datetime
melted_df['Year_date'] = pd.to_datetime(melted_df['Year'], format='%Y', errors='coerce')

print(melted_df.dtypes)
melted_df.head()

Country               object
Year                   int64
Population           float64
Year_date     datetime64[ns]
dtype: object

  Country  Year  Population  Year_date
0     USA  2000           0 2000-01-01
1   China  2000           1 2000-01-01
2   India  2000           1 2000-01-01
3  Brazil  2000           0 2000-01-01
4  Russia  2000           0 2000-01-01

## `rename`

In [67]:
# Renomeando a coluna 'Country' para 'Country_Name'
renamed_df = melted_df.rename(columns={'Country': 'Country_Name'})

print(renamed_df)

      Country_Name  Year  Population  Year_date
0              USA  2000           0 2000-01-01
1            China  2000           1 2000-01-01
2            India  2000           1 2000-01-01
3           Brazil  2000           0 2000-01-01
4           Russia  2000           0 2000-01-01
5            Japan  2000           0 2000-01-01
6          Germany  2000           0 2000-01-01
7   United Kingdom  2000           0 2000-01-01
8           France  2000           0 2000-01-01
9              USA  2010           0 2010-01-01
10           China  2010           1 2010-01-01
11           India  2010           1 2010-01-01
12          Brazil  2010           0 2010-01-01
13          Russia  2010           0 2010-01-01
14           Japan  2010           0 2010-01-01
15         Germany  2010           0 2010-01-01
16  United Kingdom  2010           0 2010-01-01
17          France  2010           0 2010-01-01
18             USA  2020           0 2020-01-01
19           China  2020           1 2020-01-01
20           India  2020           1 2020-01-01
21          Brazil  2020           0 2020-01-01
22          Russia  2020           0 2020-01-01
23           Japan  2020           0 2020-01-01
24         Germany  2020           0 2020-01-01
25  United Kingdom  2020           0 2020-01-01
26          France  2020           0 2020-01-01

### `sort_values`

In [68]:
# Ordenando o DataFrame por 'Population_2010' em ordem decrescente
sorted_df = renamed_df.sort_values(by='Population', ascending=False)

print(sorted_df)

      Country_Name  Year  Population  Year_date
19           China  2020           1 2020-01-01
20           India  2020           1 2020-01-01
10           China  2010           1 2010-01-01
1            China  2000           1 2000-01-01
11           India  2010           1 2010-01-01
2            India  2000           1 2000-01-01
26          France  2020           0 2020-01-01
17          France  2010           0 2010-01-01
8           France  2000           0 2000-01-01
18             USA  2020           0 2020-01-01
9              USA  2010           0 2010-01-01
0              USA  2000           0 2000-01-01
21          Brazil  2020           0 2020-01-01
12          Brazil  2010           0 2010-01-01
3           Brazil  2000           0 2000-01-01
22          Russia  2020           0 2020-01-01
13          Russia  2010           0 2010-01-01
14           Japan  2010           0 2010-01-01
5            Japan  2000           0 2000-01-01
23           Japan  2020           0 2020-01-01
24         Germany  2020           0 2020-01-01
6          Germany  2000           0 2000-01-01
15         Germany  2010           0 2010-01-01
25  United Kingdom  2020           0 2020-01-01
16  United Kingdom  2010           0 2010-01-01
7   United Kingdom  2000           0 2000-01-01
4           Russia  2000           0 2000-01-01

### `reset_index`

In [69]:
# Resetando o índice
reset_df = sorted_df.reset_index(drop=True)
print(reset_df)

      Country_Name  Year  Population  Year_date
0            China  2020           1 2020-01-01
1            India  2020           1 2020-01-01
2            China  2010           1 2010-01-01
3            China  2000           1 2000-01-01
4            India  2010           1 2010-01-01
5            India  2000           1 2000-01-01
6           France  2020           0 2020-01-01
7           France  2010           0 2010-01-01
8           France  2000           0 2000-01-01
9              USA  2020           0 2020-01-01
10             USA  2010           0 2010-01-01
11             USA  2000           0 2000-01-01
12          Brazil  2020           0 2020-01-01
13          Brazil  2010           0 2010-01-01
14          Brazil  2000           0 2000-01-01
15          Russia  2020           0 2020-01-01
16          Russia  2010           0 2010-01-01
17           Japan  2010           0 2010-01-01
18           Japan  2000           0 2000-01-01
19           Japan  2020           0 2020-01-01
20         Germany  2020           0 2020-01-01
21         Germany  2000           0 2000-01-01
22         Germany  2010           0 2010-01-01
23  United Kingdom  2020           0 2020-01-01
24  United Kingdom  2010           0 2010-01-01
25  United Kingdom  2000           0 2000-01-01
26          Russia  2000           0 2000-01-01

### `set_index`

In [70]:
# Definindo 'Country_Name' como o novo índice
indexed_df = reset_df.set_index('Country_Name')
print(indexed_df)

                Year  Population  Year_date
Country_Name
China           2020           1 2020-01-01
India           2020           1 2020-01-01
China           2010           1 2010-01-01
China           2000           1 2000-01-01
India           2010           1 2010-01-01
India           2000           1 2000-01-01
France          2020           0 2020-01-01
France          2010           0 2010-01-01
France          2000           0 2000-01-01
USA             2020           0 2020-01-01
USA             2010           0 2010-01-01
USA             2000           0 2000-01-01
Brazil          2020           0 2020-01-01
Brazil          2010           0 2010-01-01
Brazil          2000           0 2000-01-01
Russia          2020           0 2020-01-01
Russia          2010           0 2010-01-01
Japan           2010           0 2010-01-01
Japan           2000           0 2000-01-01
Japan           2020           0 2020-01-01
Germany         2020           0 2020-01-01
Germany         2000           0 2000-01-01
Germany         2010           0 2010-01-01
United Kingdom  2020           0 2020-01-01
United Kingdom  2010           0 2010-01-01
United Kingdom  2000           0 2000-01-01
Russia          2000           0 2000-01-01

### `merge`

how{‘left’, ‘right’, ‘outer’, ‘inner’, ‘cross’}, default: ‘inner’

Tipo de junção (merge) a ser realizada.

* left: usa apenas as chaves do DataFrame da esquerda, semelhante a um left outer join em SQL; preserva a ordem das chaves.
* right: usa apenas as chaves do DataFrame da direita, semelhante a um right outer join em SQL; preserva a ordem das chaves.
* outer: usa a união das chaves de ambos os DataFrames, semelhante a um full outer join em SQL; ordena as chaves em ordem lexicográfica.
* inner: usa a interseção das chaves de ambos os DataFrames, semelhante a um inner join em SQL; preserva a ordem das chaves do DataFrame da esquerda.
* cross: cria o produto cartesiano dos dois DataFrames, preservando a ordem das chaves do DataFrame da esquerda.

In [71]:
# Criando um segundo DataFrame para junção
continent = {'Country_Name': ['USA', 'China', 'India', 'Brazil'],
         'Continent': ["America", "Asia", "Asia", "America"]}
df_continent = pd.DataFrame(continent)
print("Segundo data Frame")
print(df_continent)

# Realizando a junção com base na coluna 'Country'
merged_df = pd.merge(reset_df, df_continent, on='Country_Name', how = 'inner')

print("\n\nDataFrame após o Merge")
print(merged_df)

Segundo data Frame
  Country_Name Continent
0          USA   America
1        China      Asia
2        India      Asia
3       Brazil   America


DataFrame após o Merge
   Country_Name  Year  Population  Year_date Continent
0         China  2020           1 2020-01-01      Asia
1         India  2020           1 2020-01-01      Asia
2         China  2010           1 2010-01-01      Asia
3         China  2000           1 2000-01-01      Asia
4         India  2010           1 2010-01-01      Asia
5         India  2000           1 2000-01-01      Asia
6           USA  2020           0 2020-01-01   America
7           USA  2010           0 2010-01-01   America
8           USA  2000           0 2000-01-01   America
9        Brazil  2020           0 2020-01-01   America
10       Brazil  2010           0 2010-01-01   America
11       Brazil  2000           0 2000-01-01   America

`how = left`

In [72]:
# Realizando a junção com base na coluna 'Country'
merged_df = pd.merge(reset_df, df_continent, on='Country_Name', how = 'left')

print("\n\nDataFrame após o Merge")
print(merged_df)

DataFrame após o Merge
      Country_Name  Year  Population  Year_date Continent
0            China  2020           1 2020-01-01      Asia
1            India  2020           1 2020-01-01      Asia
2            China  2010           1 2010-01-01      Asia
3            China  2000           1 2000-01-01      Asia
4            India  2010           1 2010-01-01      Asia
5            India  2000           1 2000-01-01      Asia
6           France  2020           0 2020-01-01       NaN
7           France  2010           0 2010-01-01       NaN
8           France  2000           0 2000-01-01       NaN
9              USA  2020           0 2020-01-01   America
10             USA  2010           0 2010-01-01   America
11             USA  2000           0 2000-01-01   America
12          Brazil  2020           0 2020-01-01   America
13          Brazil  2010           0 2010-01-01   America
14          Brazil  2000           0 2000-01-01   America
15          Russia  2020           0 2020-01-01       NaN
16          Russia  2010           0 2010-01-01       NaN
17           Japan  2010           0 2010-01-01       NaN
18           Japan  2000           0 2000-01-01       NaN
19           Japan  2020           0 2020-01-01       NaN
20         Germany  2020           0 2020-01-01       NaN
21         Germany  2000           0 2000-01-01       NaN
22         Germany  2010           0 2010-01-01       NaN
23  United Kingdom  2020           0 2020-01-01       NaN
24  United Kingdom  2010           0 2010-01-01       NaN
25  United Kingdom  2000           0 2000-01-01       NaN
26          Russia  2000           0 2000-01-01       NaN

#### Agora com todos os países

In [73]:
# Criando um segundo DataFrame para junção
continent = {'Country_Name': ['USA', 'China', 'India', 'Brazil', 'France','Russia','Japan','Germany','United Kingdom'],
         'Continent': ["America", "Asia", "Asia", "America","Europe","Asia","Asia","Europe","Europe"]}
df_continent = pd.DataFrame(continent)

# Realizando a junção com base na coluna 'Country_Name'
merged_df = pd.merge(reset_df, df_continent, on='Country_Name')

print(merged_df)

      Country_Name  Year  Population  Year_date Continent
0            China  2020           1 2020-01-01      Asia
1            India  2020           1 2020-01-01      Asia
2            China  2010           1 2010-01-01      Asia
3            China  2000           1 2000-01-01      Asia
4            India  2010           1 2010-01-01      Asia
5            India  2000           1 2000-01-01      Asia
6           France  2020           0 2020-01-01    Europe
7           France  2010           0 2010-01-01    Europe
8           France  2000           0 2000-01-01    Europe
9              USA  2020           0 2020-01-01   America
10             USA  2010           0 2010-01-01   America
11             USA  2000           0 2000-01-01   America
12          Brazil  2020           0 2020-01-01   America
13          Brazil  2010           0 2010-01-01   America
14          Brazil  2000           0 2000-01-01   America
15          Russia  2020           0 2020-01-01      Asia
16          Russia  2010           0 2010-01-01      Asia
17           Japan  2010           0 2010-01-01      Asia
18           Japan  2000           0 2000-01-01      Asia
19           Japan  2020           0 2020-01-01      Asia
20         Germany  2020           0 2020-01-01    Europe
21         Germany  2000           0 2000-01-01    Europe
22         Germany  2010           0 2010-01-01    Europe
23  United Kingdom  2020           0 2020-01-01    Europe
24  United Kingdom  2010           0 2010-01-01    Europe
25  United Kingdom  2000           0 2000-01-01    Europe
26          Russia  2000           0 2000-01-01      Asia

### `group_by`

In [74]:
# Agrupando por 'Year' e calculando a soma da população
grouped_df = merged_df.groupby('Continent')['Population'].sum()

print(grouped_df)

Continent
America   2
Asia      8
Europe    2
Name: Population, dtype: float64

### `crosstab` *frequência*

In [75]:
# Calculando uma tabulação cruzada entre 'Country' e 'Year'
cross_tab = pd.crosstab(merged_df['Continent'], merged_df['Year'])

print(cross_tab)

Year       2000  2010  2020
Continent
America       2     2     2
Asia          4     4     4
Europe        3     3     3

### `crosstab` *média*

In [82]:
# Calculando uma tabulação cruzada entre 'Country' e 'Year'
cross_tab = pd.crosstab(merged_df['Continent'], merged_df['Year'],values=merged_df['Population'],aggfunc="mean")

print(cross_tab)

Year       2000  2010  2020
Continent
America       0     0     0
Asia          1     1     1
Europe        0     0     0

### `pivot_table`

In [83]:
# Criando uma tabela dinâmica com 'Country' como índice, 'Year' como colunas e 'Population_2010' como valores
pivot_df = merged_df.pivot_table(index='Continent', columns='Year', values='Population', aggfunc='mean')

print(pivot_df)

Year       2000  2010  2020
Continent
America       0     0     0
Asia          1     1     1
Europe        0     0     0

### Multi-Index

The main difference between crosstab() and pivot_table() in Pandas lies in their intended use and the flexibility they offer for data aggregation and summarization:

```crosstab()``` is specifically designed for computing a cross-tabulation of two or more factors.
It provides a convenient way to calculate frequency counts of specific factors in the DataFrame.
It is a specialized function mainly used for computing simple frequency tables.

```pivot_table()``` is a more general-purpose function that creates a spreadsheet-style pivot table as a DataFrame.
It allows for more flexibility in specifying index, columns, and aggregation functions.
It is more powerful and versatile than crosstab() as it can handle more complex data reshaping and aggregation tasks.
It can handle missing values more gracefully by providing options for handling them during aggregation.
In summary, while both crosstab() and pivot_table() can be used for reshaping and summarizing data, crosstab() is specialized for computing frequency tables, while pivot_table() is a more general tool for creating pivot tables with more flexibility in data aggregation and handling missing values.

In [84]:
# Criando uma tabela dinâmica com 'Country' e 'Continent' como índices, 'Year' como colunas e 'Population_2010' como valores
pivot_df = merged_df.pivot_table(index=['Continent','Country_Name'], columns='Year', values='Population', aggfunc='mean')

print(pivot_df)

Year                      2000  2010  2020
Continent Country_Name
America   Brazil             0     0     0
          USA                0     0     0
Asia      China              1     1     1
          India              1     1     1
          Japan              0     0     0
          Russia             0     0     0
Europe    France             0     0     0
          Germany            0     0     0
          United Kingdom     0     0     0

### `resample`

In [87]:
#Chose a country
br_df = merged_df[merged_df["Country_Name"]=="Brazil"]

# set Date at the end of the Year
br_df['Year_date'] = pd.to_datetime(br_df['Year'].astype(str) + '-12-31', format='%Y-%m-%d', errors='coerce')

# set Index
br_df.set_index('Year_date', inplace=True)

print("Data Frame pronto para o resample, mas com os anos faltando")
print(br_df)

Data Frame pronto para o resample, mas com os anos faltando
           Country_Name  Year  Population Continent
Year_date
2020-12-31       Brazil  2020           0   America
2010-12-31       Brazil  2010           0   America
2000-12-31       Brazil  2000           0   America

C:\Users\gkr14\AppData\Local\Temp\ipykernel_15232\3446776318.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  br_df['Year_date'] = pd.to_datetime(br_df['Year'].astype(str) + '-12-31', format='%Y-%m-%d', errors='coerce')

In [88]:
# Resample from 10-year to yearly frequency
# Interpolate to distribute yearly values evenly across years
df_yearly = br_df.resample('Y').interpolate('linear')  # Resample yearly data to monthly and fill missing values
print("\n\nData Frame com os valores numéricos interpolados")
print(df_yearly.head)

Data Frame com os valores numéricos interpolados
<bound method NDFrame.head of            Country_Name  Year  Population Continent
Year_date
2000-12-31       Brazil 2,000           0   America
2001-12-31          NaN 2,001           0       NaN
2002-12-31          NaN 2,002           0       NaN
2003-12-31          NaN 2,003           0       NaN
2004-12-31          NaN 2,004           0       NaN
2005-12-31          NaN 2,005           0       NaN
2006-12-31          NaN 2,006           0       NaN
2007-12-31          NaN 2,007           0       NaN
2008-12-31          NaN 2,008           0       NaN
2009-12-31          NaN 2,009           0       NaN
2010-12-31       Brazil 2,010           0   America
2011-12-31          NaN 2,011           0       NaN
2012-12-31          NaN 2,012           0       NaN
2013-12-31          NaN 2,013           0       NaN
2014-12-31          NaN 2,014           0       NaN
2015-12-31          NaN 2,015           0       NaN
2016-12-31          NaN 2,016           0       NaN
2017-12-31          NaN 2,017           0       NaN
2018-12-31          NaN 2,018           0       NaN
2019-12-31          NaN 2,019           0       NaN
2020-12-31       Brazil 2,020           0   America>

C:\Users\gkr14\AppData\Local\Temp\ipykernel_15232\3071040946.py:3: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  df_yearly = br_df.resample('Y').interpolate('linear')  # Resample yearly data to monthly and fill missing values
C:\Users\gkr14\AppData\Local\Temp\ipykernel_15232\3071040946.py:3: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_yearly = br_df.resample('Y').interpolate('linear')  # Resample yearly data to monthly and fill missing values

`ffill` propaga o último valor

In [89]:
# Forward fill 'Country_Name' and 'Continent' column
non_numeric_columns=df_yearly.select_dtypes(include='object').columns
df_yearly[non_numeric_columns] = df_yearly[non_numeric_columns].ffill()

print("\n\nData Frame completo")
print(df_yearly)

Data Frame completo
           Country_Name  Year  Population Continent
Year_date
2000-12-31       Brazil 2,000           0   America
2001-12-31       Brazil 2,001           0   America
2002-12-31       Brazil 2,002           0   America
2003-12-31       Brazil 2,003           0   America
2004-12-31       Brazil 2,004           0   America
2005-12-31       Brazil 2,005           0   America
2006-12-31       Brazil 2,006           0   America
2007-12-31       Brazil 2,007           0   America
2008-12-31       Brazil 2,008           0   America
2009-12-31       Brazil 2,009           0   America
2010-12-31       Brazil 2,010           0   America
2011-12-31       Brazil 2,011           0   America
2012-12-31       Brazil 2,012           0   America
2013-12-31       Brazil 2,013           0   America
2014-12-31       Brazil 2,014           0   America
2015-12-31       Brazil 2,015           0   America
2016-12-31       Brazil 2,016           0   America
2017-12-31       Brazil 2,017           0   America
2018-12-31       Brazil 2,018           0   America
2019-12-31       Brazil 2,019           0   America
2020-12-31       Brazil 2,020           0   America

## Referências

| Método           | Descrição                                         | Link na Documentação                                           |
|------------------|---------------------------------------------------|---------------------------------------------------------------|
| apply()          | Aplica uma função ao longo de um eixo do DataFrame | [apply()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html) |
| astype()         | Converte o tipo de dados de uma Series           | [astype()](https://pandas.pydata.org/docs/reference/api/pandas.Series.astype.html) |
| concat()         | Concatena DataFrames ao longo de um eixo específico | [concat()](https://pandas.pydata.org/docs/reference/api/pandas.concat.html) |
| crosstab()       | Calcula uma tabulação cruzada de dois ou mais fatores | [crosstab()](https://pandas.pydata.org/docs/reference/api/pandas.crosstab.html) |
| drop()           | Descarta rótulos especificados de linhas ou colunas | [drop()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html) |
| drop_duplicates()| Remove linhas duplicadas de um DataFrame         | [drop_duplicates()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop_duplicates.html) |
| fillna()         | Preenche valores NA/Nan usando o método especificado | [fillna()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html) |
| ffill()          | Preenche os valores ausentes para a frente usando o último valor válido conhecido | [ffill()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.ffill.html) |
| groupby()        | Agrupa DataFrame usando um mapeador ou por uma Series de colunas | [groupby()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html) |
| iloc[]           | Acessa um grupo de linhas e colunas por posição inteira | [iloc[]](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html) |
| interpolate()    | Preenche valores NA/Nan interpolando entre valores válidos conhecidos | [interpolate()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.interpolate.html) |
| isin()           | Verifica se os elementos de um DataFrame estão contidos em outro DataFrame ou Series | [isin()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isin.html) |
| loc[]            | Acessa um grupo de linhas e colunas por rótulos  | [loc[]](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html) |
| merge()          | Junta objetos DataFrame realizando uma operação de junção estilo banco de dados | [merge()](https://pandas.pydata.org/docs/reference/api/pandas.merge.html) |
| melt()           | Despivota um DataFrame de formato largo para longo | [melt()](https://pandas.pydata.org/docs/reference/api/pandas.melt.html) |
| pivot_table()    | Cria uma tabela dinâmica no estilo de uma planilha como um DataFrame | [pivot_table()](https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html) |
| rename()         | Renomeia colunas ou índices de um DataFrame     | [rename()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html) |
| resample()       | Realiza uma amostragem temporal em uma série de dados | [resample()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.resample.html) |
| reset_index()    | Redefine o índice de um DataFrame para o padrão numérico | [reset_index()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html) |
select_dtypes() |Selecionar colunas do DF segundo o tipo| [select_dtypes()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.select_dtypes.html)|
| set_index()      | Define o índice do DataFrame usando colunas existentes | [set_index()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html) |
| sort_values()    | Ordena DataFrame pelos valores ao longo de um eixo específico | [sort_values()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html) |
| to_datetime()    | Converte argumento para datetime                 | [to_datetime()](https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html) |
| unique()         | Obtém valores únicos em uma Series               | [unique()](https://pandas.pydata.org/docs/reference/api/pandas.Series.unique.html) |
| value_counts()   | Conta valores únicos em uma Series               | [value_counts()](https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html) |



## Fique Conectado

- [![YouTube](https://img.icons8.com/?size=40&id=19318&format=png&color=000000)](https://www.youtube.com/@LigaDataScience/videos)  
  Explore nossos vídeos educacionais e webinars sobre ciência de dados, machine learning e inteligência artificial. Inscreva-se para não perder nenhuma atualização!

- [![LinkedIn](https://img.icons8.com/?size=40&id=13930&format=png&color=000000)](https://www.linkedin.com/company/liga-data-science-ufpr/)  
  Siga-nos no LinkedIn para as últimas novidades, oportunidades de carreira e networking profissional no campo da ciência de dados.

- [![Instagram](https://img.icons8.com/?size=40&id=32323&format=png&color=000000)](https://www.instagram.com/ligadatascience/)  
  Confira nosso Instagram para conteúdos dos bastidores, destaques de eventos e o dia a dia da Liga Data Science. Faça parte da nossa jornada!
  

  
## Autores

<a href="https://www.linkedin.com/in/eduardopecora/" target="_blank">Eduardo Pecora</a>

## Log de modificações

| Data | Versão | Modificado por | Descrição |
| -----------| ------- | ---------- | ---------------------------------- |
| 13-05-2024       | 1.0   | Eduardo Pecora    | Estrutura Aula        |

<h3 align="center"> (c) Liga Data Science / UFPR 2024. All rights reserved. <h3/>